PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX lblodmow: <http://data.lblod.info/vocabularies/mobiliteit/>
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>

DELETE {
    GRAPH ?g {
        ?s a lblodmow:TrafficMeasureConcept;
        ext:valid ?o .
        }
    }

INSERT {
    GRAPH ?g {
        ?s a mobiliteit:Mobiliteitmaatregelconcept;
        ext:valid ?o .
    }
}

WHERE {
    GRAPH ?g {
        ?s a lblodmow:TrafficMeasureConcept;
        ext:valid ?o .
    }
}

;

DELETE {
    GRAPH ?g {
        ?s a ext:Concept;
        ext:valid ?o .
        }
    }

INSERT {
    GRAPH ?g {
        ?s a mobiliteit:Verkeerstekenconcept;
        ext:valid ?o .
    }
}

WHERE {
    GRAPH ?g {
        ?s a ext:Concept;
        ext:valid ?o .
    }
}