DELETE {
GRAPH <http://mu.semte.ch/graphs/mow/registry> {
?s <http://mu.semte.ch/vocabularies/core/uuid> ?definition
}
}
INSERT { 
GRAPH <http://mu.semte.ch/graphs/mow/registry> {
?s <http://mu.semte.ch/vocabularies/core/uuid> ?newDefinition 
}
}
WHERE {
?s <http://mu.semte.ch/vocabularies/core/uuid> ?definition
      FILTER langMatches( lang(?definition), "*" )
BIND(STR(?definition) AS ?newDefinition)
}