PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
INSERT {
  GRAPH <http://mu.semte.ch/graphs/mow/registry> {
    ?measure skos:prefLabel ?fullLabel
  }
}
WHERE {
  SELECT ?measure GROUP_CONCAT(?label; SEPARATOR="-") AS ?fullLabel
  WHERE {
  ?measure ext:relation ?relation.
  ?relation ext:concept ?concept.
  ?concept skos:prefLabel ?label.
  }
}