PREFIX ext: <http://mu.semte.ch/vocabularies/ext/>
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX qb: <http://purl.org/linked-data/cube#>


DELETE {
    GRAPH ?g {
        ?trafficMeasure ext:relation ?relation
    }
}

INSERT {
    GRAPH ?g {
        ?trafficSignConcept mobiliteit:heeftMaatregelconcept ?trafficMeasure
    }
}

WHERE {
    GRAPH ?g {
        ?trafficMeasure ext:relation ?relation.
        ?relation <http://mu.semte.ch/vocabularies/ext/concept> ?trafficSignConcept.
    }
}

