PREFIX cidoc: <http://www.cidoc-crm.org/cidoc-crm/>
PREFIX tribont: <https://w3id.org/tribont/core#>
PREFIX mu: <http://mu.semte.ch/vocabularies/core/>

INSERT DATA {
  GRAPH  <http://mu.semte.ch/graphs/public> {
    <http://data.lblod.info/tribont-shapes/1cddd186-6018-4d12-84d6-f1a5d01affde> a tribont:Shape;
            mu:uuid "1cddd186-6018-4d12-84d6-f1a5d01affde";
            cidoc:P2_has_type "Driehoekig".
    <http://data.lblod.info/tribont-shapes/0e0897d1-5c74-47ae-9868-adecbde6f2f3> a tribont:Shape;
            mu:uuid "0e0897d1-5c74-47ae-9868-adecbde6f2f3";
            cidoc:P2_has_type "Achthoekig".
    <http://data.lblod.info/tribont-shapes/2481e377-1a89-4e25-9c58-1b509e0f7d74> a tribont:Shape;
            mu:uuid "2481e377-1a89-4e25-9c58-1b509e0f7d74";
            cidoc:P2_has_type "Rond".
    <http://data.lblod.info/tribont-shapes/322852b4-ec7b-4ca2-b267-4fcc263fa0d7> a tribont:Shape;
            mu:uuid "322852b4-ec7b-4ca2-b267-4fcc263fa0d7";
            cidoc:P2_has_type "Ruitvormig".
    <http://data.lblod.info/tribont-shapes/09675ff8-bb7d-4e76-9766-61816b993f25>  a tribont:Shape;
            mu:uuid "09675ff8-bb7d-4e76-9766-61816b993f25";
            cidoc:P2_has_type "Klein ruitvormig".
    <http://data.lblod.info/tribont-shapes/a5a1b947-1c34-40df-8842-707de418adb8>  a tribont:Shape;
            mu:uuid "a5a1b947-1c34-40df-8842-707de418adb8";
            cidoc:P2_has_type "Groot bord".
    <http://data.lblod.info/tribont-shapes/4f445b8f-98ce-4621-b671-009a1acb13a6>  a tribont:Shape;
            mu:uuid "4f445b8f-98ce-4621-b671-009a1acb13a6";
            cidoc:P2_has_type "Wegwijzer met puntvorm".
    <http://data.lblod.info/tribont-shapes/10e54ea1-ea7b-4c19-ae90-eb7e34158073> a tribont:Shape;
            mu:uuid "10e54ea1-ea7b-4c19-ae90-eb7e34158073";
            cidoc:P2_has_type "Wegomlegging rechtdoor in puntvorm (fig. 10-1-66)".
  }
}
