PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>

INSERT {
  graph ?h {
    ?s a foaf:Document .
  }
}
WHERE {
  graph ?g {
    ?s a foaf:Image .
  } BIND (?g AS ?h)
}