PREFIX dct: <http://purl.org/dc/terms/>
PREFIX mobiliteit: <https://data.vlaanderen.be/ns/mobiliteit#>
PREFIX org: <http://www.w3.org/ns/org#>
PREFIX lblodmow: <http://data.lblod.info/vocabularies/mobiliteit/>


INSERT {
    GRAPH ?g {
    ?s a mobiliteit:VerkeerstekenConcept .
}
}
WHERE {
    GRAPH ?g {
    ?s a mobiliteit:VerkeersbordConcept .
}
}

;

DELETE {
    GRAPH ?g {
    ?s org:classification ?o .
    }
}
INSERT{
    GRAPH ?g {
    ?s dct:type ?o .
    }
}
WHERE{
    GRAPH ?g {
    ?s a mobiliteit:VerkeersbordConcept ;
    org:classification ?o .
} 
}

;

DELETE {
    GRAPH ?g {
        ?s lblodmow:heeftOnderBordConcept ?o .
    }
}
INSERT {
    GRAPH ?g {
        ?s mobiliteit:heeftOnderbordConcept ?o .
    }
}
WHERE {
    GRAPH ?g {
    ?s a mobiliteit:VerkeersbordConcept ;
    lblodmow:heeftOnderbordConcept ?o .
}
}