PREFIX variables: <http://lblod.data.gift/vocabularies/variables/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
INSERT {
    GRAPH ?g {
        ?variable variables:required "true"^^xsd:boolean.
    }
} WHERE {
    GRAPH ?g {
        ?variable a variables:Variable.
        FILTER NOT EXISTS {
            ?variable variables:required ?required.
        }
    }
}